# Generated by Django 6.0.6 on 2026-07-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='gitlink',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='tech',
            field=models.CharField(default='Not Specified', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='python', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.TextField(max_length=1000),
        ),
    ]
