# Generated by Django 6.0.6 on 2026-07-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_gitlink_job_link_job_tech_job_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='tech',
        ),
        migrations.AddField(
            model_name='job',
            name='tech',
            field=models.ManyToManyField(to='jobs.technology'),
        ),
    ]
