# Generated by Django 6.0.6 on 2026-07-06 20:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_technology_remove_job_tech_job_tech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
