# Generated by Django 6.0.6 on 2026-07-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_certificate_education_experience_profile_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(blank=True, help_text='FontAwesome icon class, e.g. fa-brands fa-nodejs (leave blank to auto-assign)', max_length=100),
        ),
    ]
