# Generated by Django 6.0.6 on 2026-07-07 18:19

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_skill_icon_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(storage=jobs.models.get_resume_storage, upload_to='resumes/'),
        ),
    ]
