# Generated by Django 6.0.6 on 2026-07-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_job_slug_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
